const nu = null;
const bl = "#000000"
const wb = "#EDEEF7"

export const atkIcon = [
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu],
    [nu, wb, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, wb, bl, wb, nu],
    [wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, bl, bl, bl, wb, wb, bl, bl, wb],
    [wb, bl, wb, wb, wb, wb, wb, wb, wb, bl, bl, bl, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, bl, bl, bl, wb, bl, bl, bl, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, wb, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, wb, bl, bl, bl, wb, wb, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, wb, wb, wb, wb, wb, bl, bl, wb],
    [nu, wb, bl, wb, wb, bl, bl, wb, bl, bl, wb, wb, wb, wb, wb, bl, wb, nu],
    [nu, wb, bl, bl, wb, wb, wb, wb, wb, bl, wb, wb, wb, wb, bl, bl, wb, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu]
];

export const defIcon = [
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu],
    [nu, wb, bl, wb, wb, bl, bl, wb, wb, wb, wb, bl, bl, wb, wb, bl, wb, nu],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb],
    [nu, wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb, nu],
    [nu, wb, bl, bl, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, bl, bl, wb, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu]
];

export const minionIcon = [
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, bl, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, wb, bl, bl, wb, wb, wb, wb, bl, wb, wb, wb, wb, wb, bl, bl, wb, nu],
    [nu, wb, bl, wb, wb, wb, wb, wb, bl, bl, bl, wb, wb, wb, wb, bl, wb, nu],
    [wb, bl, bl, wb, wb, wb, wb, wb, wb, bl, bl, bl, wb, wb, wb, bl, bl, wb],
    [wb, bl, wb, wb, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, wb, bl, bl, bl, bl, wb, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, wb, wb, bl, bl, wb, wb, bl, wb, wb, wb, bl, wb],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb],
    [nu, wb, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, wb, nu],
    [nu, wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu]
];

export const scytheIcon = [
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, wb, bl, bl, wb, bl, wb, bl, bl, bl, bl, wb, wb, wb, bl, bl, wb, nu],
    [nu, wb, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb, nu],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, wb, wb, wb, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, wb, wb, wb, wb, wb, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, wb, wb, wb, wb, wb, wb, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, bl, wb, wb, wb, wb, wb, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, bl, wb, wb, bl, wb, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb],
    [nu, wb, bl, wb, wb, bl, wb, wb, wb, wb, wb, wb, wb, wb, wb, bl, wb, nu],
    [nu, wb, bl, bl, wb, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu]
];

export const buffIcon = [
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, bl, bl, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, wb, bl, bl, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, bl, bl, wb, nu],
    [nu, wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb, nu],
    [wb, bl, bl, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, bl, bl, wb],
    [wb, bl, wb, wb, wb, bl, bl, bl, bl, bl, bl, bl, bl, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, wb, wb, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, wb, wb, bl, wb],
    [wb, bl, bl, wb, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, wb, bl, bl, wb],
    [nu, wb, bl, wb, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, wb, bl, wb, nu],
    [nu, wb, bl, bl, wb, wb, wb, bl, bl, bl, bl, wb, wb, wb, bl, bl, wb, nu],
    [nu, nu, wb, bl, bl, wb, wb, wb, wb, wb, wb, wb, wb, bl, bl, wb, nu, nu],
    [nu, nu, nu, wb, bl, bl, bl, wb, wb, wb, wb, bl, bl, bl, wb, nu, nu, nu],
    [nu, nu, nu, nu, wb, wb, bl, bl, bl, bl, bl, bl, wb, wb, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, wb, wb, wb, wb, wb, wb, nu, nu, nu, nu, nu, nu]
];

export const deckIcon = [
    [bl, bl, nu, nu, bl, bl, bl, bl, bl, nu, nu, bl, bl],
    [bl, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, bl],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, bl, nu, nu, nu, nu, bl, nu, nu, nu, nu, bl, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [bl, nu, nu, bl, nu, bl, bl, bl, nu, bl, nu, nu, bl],
    [bl, nu, nu, nu, bl, nu, nu, nu, bl, nu, nu, nu, bl],
    [bl, nu, nu, bl, nu, bl, bl, bl, nu, bl, nu, nu, bl],
    [bl, nu, bl, bl, nu, bl, nu, bl, nu, bl, bl, nu, bl],
    [bl, nu, nu, bl, nu, bl, bl, bl, nu, bl, nu, nu, bl],
    [bl, nu, nu, nu, bl, nu, nu, nu, bl, nu, nu, nu, bl],
    [bl, nu, nu, bl, nu, bl, bl, bl, nu, bl, nu, nu, bl],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, bl, nu, nu, nu, nu, bl, nu, nu, nu, nu, bl, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [bl, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, bl],
    [bl, bl, nu, nu, bl, bl, bl, bl, bl, nu, nu, bl, bl],
];

export const graveyardIcon = [
    [bl, bl, nu, nu, bl, bl, bl, bl, bl, nu, nu, bl, bl],
    [bl, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, bl],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, bl, bl, bl, bl, bl, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [nu, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, nu],
    [bl, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, bl],
    [bl, nu, nu, nu, nu, nu, bl, nu, nu, nu, nu, nu, bl],
    [bl, nu, nu, nu, nu, bl, bl, bl, nu, nu, nu, nu, bl],
    [bl, nu, nu, nu, bl, bl, bl, bl, bl, nu, nu, nu, bl],
    [bl, nu, nu, nu, bl, bl, bl, bl, bl, nu, nu, nu, bl],
    [bl, nu, nu, bl, bl, bl, bl, bl, bl, bl, nu, nu, bl],
    [bl, nu, nu, bl, bl, bl, bl, bl, bl, bl, nu, nu, bl],
    [nu, nu, nu, bl, bl, bl, bl, bl, bl, bl, nu, nu, nu],
    [nu, nu, nu, bl, bl, bl, bl, bl, bl, bl, nu, nu, nu],
    [nu, nu, nu, bl, bl, bl, bl, bl, bl, bl, nu, nu, nu],
    [nu, nu, bl, bl, bl, bl, bl, bl, bl, bl, bl, nu, nu],
    [nu, nu, bl, bl, bl, bl, bl, bl, bl, bl, bl, nu, nu],
    [nu, nu, bl, bl, bl, bl, bl, bl, bl, bl, bl, nu, nu],
    [bl, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, nu, bl],
    [bl, bl, nu, nu, bl, bl, bl, bl, bl, nu, nu, bl, bl],
];